### ISSUE TITLE
postgresql-embedded fails to start in travis environment

### ISSUE THREAD

**Issue by ArchDev** [yandex-qatools/postgresql-embedded#145]
Hi there, first of all, thx for your library it worked great for the last two years for me.

Currently, I have a public project which uses postgres-embedded and builds it at CI, but after some changes (probably in Travis ci agents), my test code cannot connect to Postgres on build machines. I cannot reproduce it locally and not sure how to get more information about what's going on.

Here is build log https://travis-ci.org/ArchDev/akka-http-rest/jobs/440496384#L796 and file where I use the library https://github.com/ArchDev/akka-http-rest/blob/master/src/test/scala/me/archdev/utils/InMemoryPostgresStorage.scala also Travis build config https://github.com/ArchDev/akka-http-rest/blob/master/.travis.yml

This happening only on CI (worst words ever). Locally everything works great for me. Can you please help me to debug that issue?

**Comment by ilkerc** [comment]
Somehow it did had to do with the base image I was using. Maybe it was missing some runtime libraries.. I left using alpine versions and ended up using ubuntu 16.04 with preinstalled jdk.

After all, it was able to execute initdb. While maven is being executed as root I created a new user and did installation & packaging using the unprivileged user.

Anyone having the same issue, I'll paste here the wercker.yml file. Hope you wont waste hours like I did :)

```
box: mlaccetti/docker-oracle-java8-ubuntu-16.04
build:
  steps:
  - script:
      name: install required packages
      code: |
        apt-get -y update
        apt-get install -y git curl sudo
        useradd -ms /bin/bash mavenuser
  - wercker/maven:
      goals: install
      cache_repo: true
      version: 3.5.4
      sudo_user: mavenuser
```
